name: "30 Timeframe"
on:
  push:
    branches:
      - master
      - main
  schedule:
      - cron: '0 12 * * *'

jobs:
  update-data:
    - cron: '0 2 * * *'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    - cron: '0 2 * * *'
      GITHUB_PAT: ${{ secrets.GH_PAT }}      
      TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
      TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
    steps:
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Apt-get update things
        run: |
          sudo apt-get update 

      - name: Apt-get needed things
        run: |
          sudo apt-get install --no-install-recommends -y \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libudunits2-dev \
          libgdal-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          needs: |
            any::tidyverse
            any::httr
            any::remotes
            any::shiny
            any::scales
            any::treemap
            any::here
            any::jsonlite
            any::janitor
            any::quarto
            any::highcharter
            any::lubridate
            any::gt
            any::gtExtras
            any::pacman
            any::openxlsx
            any::sf
            any::xml2
            any::rvest
            any::reticulate
            any::fs
            any::countrycode
            any::progress
            any::cli
            any::digest
            any::glue
            any::vroom
            any::prettydoc
            any::DT
            any::piggyback
            any::httr2
            any::openssl
            any::priceR

      - name: "Install arrow"
        run: Rscript 'arrow.R'

      - name: "Script - Run"
        run: Rscript 'get_audiences.R' 30 "AL"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update data - $(date +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"

      - name: Sync and Force Push Changes
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Fetch latest changes
          git fetch --all

          # Determine if 'main' or 'master' exists
          if git show-ref --verify --quiet refs/heads/main; then
            TARGET_BRANCH="main"
          elif git show-ref --verify --quiet refs/heads/master; then
            TARGET_BRANCH="master"
          else
            echo "Neither 'main' nor 'master' branch exists. Exiting."
            exit 1
          fi

          # Check out the target branch and sync workflows
          git checkout $TARGET_BRANCH
          git checkout origin/$TARGET_BRANCH -- .github/workflows
          git add .github/workflows
          git commit -m "Continued Workflow: from $TARGET_BRANCH" || echo "No workflow changes to commit"

          # Force push changes to the determined branch
          git push --force origin $TARGET_BRANCH
